services:
  web:
    container_name: challenge-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - /app/node_modules
